apiVersion: v1
kind: Pod
metadata:
  name: hello-app-test-pod
  labels:
    app: helloapptest
spec:
  containers:
  - name: hello-app-test
    image: curlimages/curl:7.78.0
    command: ["curl"]
    args: ["http://helloapp:8080"]
  restartPolicy: Never